#!/bin/bash

# List of IP addresses to ping
IP_ADDRESSES=("192.168.1.1" "8.8.8.8" "10.0.0.5")

# Loop through the list of IPs and ping each
for IP in "${IP_ADDRESSES[@]}"
do
  ping -c 1 "$IP" &> /dev/null
  
  if [ $? -eq 0 ]; then
    echo "$IP: OK"
  else
    echo "$IP: NOOK"
  fi
done
